name: cs6220ProjectLstm
channels:
  - cogsci
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.7
  - numpy
  - ipdb
  - yaml
  - jupyter
  - librosa
  - pip
  - pip:
    - absl-py==0.8.1
    - astor==0.8.0
    - audioread==2.1.8
    - cachetools==3.1.1
    - cffi==1.13.2
    - chardet==3.0.4
    - cycler==0.10.0
    - gast==0.2.2
    - google-auth==1.7.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.25.0
    - h5py==2.10.0
    - idna==2.8
    - joblib==0.14.0
    - jupyter==1.0.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - librosa==0.7.1
    - llvmlite==0.30.0
    - markdown==3.1.1
    - matplotlib==3.1.1
    - mpmath==1.1.0
    - nose==1.3.7
    - numba==0.46.0
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - pandas==0.25.3
    - protobuf==3.10.0
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.7
    - pycparser==2.19
    - pyparsing==2.4.5
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytz==2019.3
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rsa==4.0
    - scikit-learn==0.21.3
    - scipy==1.3.2
    - soundfile==0.10.2
    - sympy==1.4
    - tensorboard==2.0.1
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - tqdm==4.38.0
    - urllib3==1.25.7
    - werkzeug==0.16.0
    - wrapt==1.11.2